### ISSUE TITLE
MultiQC error/bug?

### ISSUE THREAD

**Issue by justinkhuang** [roland-rad-lab/MoCaSeq#4]
Looking at the QC report, I noticed there were a couple issues that were found at the MultiQC step. I've pasted the log issues here. I think this might simply be a dependency issue, that needs to be updated in the docker container:

```
---- Summarizing quality control data ----
Fri Dec  4 18:19:34 CST 2020 	 timestamp: 1607127574
[INFO   ]         multiqc : This is MultiQC v1.9
[INFO   ]         multiqc : --pdf specified. Using non-interactive HTML template.
[INFO   ]         multiqc : Template    : simple
[WARNING]         multiqc : You are running MultiQC with Python 2.7.17
[WARNING]         multiqc : Please upgrade! MultiQC will soon drop support for Python < 3.6
[INFO   ]         multiqc : Searching   : /var/pipeline/mocaseq_S821_wes_test/results/QC
[ERROR  ]         multiqc : Oops! The 'somalier' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    None
============================================================
Module somalier raised an exception: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/multiqc/multiqc.py", line 567, in run
    mod = config.avail_modules[this_module].load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/multiqc/modules/somalier/__init__.py", line 3, in <module>
    from .somalier import MultiqcModule
  File "/usr/local/lib/python2.7/dist-packages/multiqc/modules/somalier/somalier.py", line 698
    cols_return.append('rgba({},{},{},{})'.format(*cols_rgb, alpha))
SyntaxError: only named arguments may follow *expression
============================================================
[INFO   ] base_recalibrator : Found 4 BaseRecalibrator reports
[INFO   ]          picard : Found 2 AlignmentSummaryMetrics reports
[INFO   ]          picard : Found 4 BaseDistributionByCycleMetrics reports
[INFO   ]          picard : Found 2 HsMetrics reports
[INFO   ]          picard : Found 2 InsertSizeMetrics reports
[INFO   ]          picard : Found 2 QualityByCycleMetrics reports
[INFO   ]          picard : Found 2 QualityScoreDistributionMetrics reports
[INFO   ]        samtools : Found 2 idxstats reports
[INFO   ]          fastqc : Found 8 reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : mocaseq_S821_wes_test/results/QC/mocaseq_S821_wes_test.html
[INFO   ]         multiqc : Data        : mocaseq_S821_wes_test/results/QC/mocaseq_S821_wes_test_data
pandoc: unrecognized option `--pdf-engine=xelatex'
Try pandoc --help for more information.
[ERROR  ]         multiqc : Error creating PDF! Pandoc returned a non-zero exit code.
[INFO   ]         multiqc : MultiQC complete
```

**Comment by NikdAK** [comment]
Hi,
thank you very much for this report. 

I am currently working on a major update, which fixes all these error messages and small problems. 
This particular issue is related to the python version, I already have it running without errors on my dev-branch.

It hope to have it all finished in about 1-2 weeks, I will let you know.
